pyodbc.cpython-38-aarch64-linux-gnu.so,sha256=oyKbcecBUReEqsZIOp2z8fpUQ_zmnmP6859ynB7ZY7k,1055088
pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
pyodbc-4.0.39.dist-info/WHEEL,sha256=oCBNUxcpJIObB7qxTwklMZvZV19pJGv6x0IkRXaUM7w,150
pyodbc-4.0.39.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.39.dist-info/RECORD,,
pyodbc-4.0.39.dist-info/METADATA,sha256=Cu1OPw2btz_Dj3huRmD0y9-0CLuocCtBc9rxYLBxYyc,3160
pyodbc-4.0.39.dist-info/top_level.txt,sha256=Rb69vS-SNN_Bfh99vX7eCcvEAJoyzowG3u4R7W36Flw,8
